[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
check_untyped_defs = True
strict_optional = True
ignore_missing_imports = True

[mypy-peft.*]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-onnx.*]
ignore_missing_imports = True

[mypy-onnxruntime.*]
ignore_missing_imports = True

[mypy-faiss.*]
ignore_missing_imports = True

[mypy-deepspeed.*]
ignore_missing_imports = True

[mypy-tensorflow.*]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-einops.*]
ignore_missing_imports = True
